---
- hosts: all

  sudo: true
  tasks:

    - name: Creando Carpeta Necesaria
      command: mkdir -p /var/lib/asterisk/firmware/iax

    - name: Parando Servicio
      service:
        name: asterisk
        state: stopped

    - name: Parando Servicio
      service:
        name: asterisk
        state: started
